name: Deploy

on:
  push:
    branches: [ production ]
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: false

permissions:
  packages: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 20

    env:
      DOCKER_BUILDKIT: 1
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_ACTOR: ${{ github.actor }}
      HOST_IP: ${{ secrets.HOST_IP }}
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: ${{ secrets.ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY }}
      ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: ${{ secrets.ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY }}
      ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: ${{ secrets.ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT }}
      POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
      COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
      EXCHANGERATE_API_KEY: ${{ secrets.EXCHANGERATE_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy with Kamal
        run: bin/kamal deploy
